#!/bin/bash

# function:monitor php-fpm status from zabbix
# License: GPL
# mail:itnihao@qq.com
# date:2013-05-30

source /etc/bashrc >/dev/null 2>&1
source /etc/profile  >/dev/null 2>&1

LOG_FILE=/var/log/zabbix/phpfpmstatus.log
curl http://127.0.0.1/phpfpmstatus >${LOG_FILE} 2>&1

pool(){
	awk '/pool/ {print $NF}' ${LOG_FILE}
}        
process_manager() {        
	awk '/process manager/ {print $NF}' ${LOG_FILE}
}  

start_since(){
    awk '/^start since:/ {print $NF}' ${LOG_FILE}
}
accepted_conn(){
    awk '/^accepted conn:/ {print $NF}' ${LOG_FILE}
}
listen_queue(){     
    awk '/^listen queue:/ {print $NF}' ${LOG_FILE}
}
max_listen_queue(){
    awk '/^max listen queue:/ {print $NF}' ${LOG_FILE}
}
listen_queue_len(){  
    awk '/^listen queue len:/ {print $NF}' ${LOG_FILE}
}
idle_processes(){
    awk '/^idle processes:/ {print $NF}' ${LOG_FILE}
}
active_processes(){
    awk '/^active processes:/ {print $NF}' ${LOG_FILE}
}
total_processes(){
    awk '/^total processes:/ {print $NF}' ${LOG_FILE}
}
max_active_processes(){
    awk '/^max active processes:/ {print $NF}' ${LOG_FILE}
}
max_children_reached(){
    awk '/^max children reached:/ {print $NF}' ${LOG_FILE}
}


case "$1" in
pool)
pool
;;
process_manager)
process_manager
;;
start_since)
start_since
;;
accepted_conn)
accepted_conn
;;
listen_queue)
listen_queue
;;
max_listen_queue)
max_listen_queue
;;
listen_queue_len)
listen_queue_len
;;
idle_processes)
idle_processes
;;
active_processes)
active_processes
;;
total_processes)
total_processes
;;
max_active_processes)
max_active_processes
;;
max_children_reached)
max_children_reached
;;
*)
echo "Usage: $0 {pool|process_manager|start_since|accepted_conn|listen_queue|max_listen_queue|listen_queue_len|idle_processes|active_processes|total_processes|max_active_processes|max_children_reached}"
esac
